---
# tasks file for samba

- name: add repo
  yum_repository:
    name: kkhbase
    description: kkhbase
    baseurl: http://mirror.kakao.com/centos/7.9.2009/os/$basearch
    state: present

#- name: install samba
#  yum: name=samba state=present enablerepo="base"
#
#- name: samba start
#  service: name=smb state=started enabled=yes
